branches:
  only:
    - master
    
# Don't start any commit builds, only scheduled
skip_tags: true
skip_non_tags: true
    
environment:
  VisualStudioVersion: 15.0
  MSBuildToolsVersion: 15.0
  DISCOVERDOTNET_GITHUB_TOKEN:
    secure: 3eTSvTaJTVGN0s2AOvYouZbUHjlp9h7pT+JFMgORZovDDD2i4q8L3Ln5ks7wBU+d
  DISCOVERDOTNET_MEETUP_TOKEN:
    secure: PAD80ZOLND+R6d20Bih7Vi9pN8taJKPIMGvtCvFmKh0=
  DISCOVERDOTNET_NETLIFY_TOKEN:
    secure: RPNadUVcxNcoERSyRyhYNpOBWV7H+d9iD4La44gyZsPgBjnHM2OU6TCzdSA+PSWH0eppMaCIgUm/2aVhmq8ixJq5tje5s3w2RRTwzXVwx8I=

image: Visual Studio 2017

build_script:
  - ps: .\build.ps1 -Target "Publish-Issues"