branches:
  only:
    - master
    
environment:
  VisualStudioVersion: 15.0
  MSBuildToolsVersion: 15.0
  DISCOVERDOTNET_GITHUB_TOKEN:
    secure: 3eTSvTaJTVGN0s2AOvYouZbUHjlp9h7pT+JFMgORZovDDD2i4q8L3Ln5ks7wBU+d
  DISCOVERDOTNET_MEETUP_TOKEN:
    secure: PAD80ZOLND+R6d20Bih7Vi9pN8taJKPIMGvtCvFmKh0=
  DISCOVERDOTNET_NETLIFY_TOKEN:
    secure: RPNadUVcxNcoERSyRyhYNpOBWV7H+d9iD4La44gyZsPgBjnHM2OU6TCzdSA+PSWH0eppMaCIgUm/2aVhmq8ixJq5tje5s3w2RRTwzXVwx8I=
  DISCOVERDOTNET_ALGOLIA_TOKEN:
    secure: AOo43zW9J/1tb72nGKo9dzapVge0KjiptMc7ntxDYqqtV+aj2I6HnOaIOLF1/2Dw

image: Visual Studio 2017

build_script:
  - ps: .\build.ps1 -Target "Publish-Site"